# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  # - osx
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
sudo: required
before_install:
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      sudo apt-get -qq update
      sudo apt-get install -y libffi-dev libssl-dev
      sudo apt-get install python-tk
    fi
install:
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 20
      g++ --version
    fi
  - "sudo pip install requests[security]"
  - "sudo pip install --only-binary=numpy numpy gdspy pyqrcode"
julia:
  - 0.5
  # - 0.6
  # - nightly
notifications:
  email: false
# uncomment the following lines to override the default test script
#script:
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("Devices"); Pkg.test("Devices"; coverage=true)'
after_success:
    # push coverage results to Coveralls
    - julia -e 'cd(Pkg.dir("Devices")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
    # push coverage results to Codecov
    - julia -e 'cd(Pkg.dir("Devices")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
    - julia -e 'Pkg.add("Documenter")'
    - julia -e 'cd(Pkg.dir("Devices")); include(joinpath("docs", "make.jl"))'
